import React from 'react';
import Head from 'next/head';
import MainLayout from '../components/MainLayout';
const AboutPage = () => {
  return (
    <>
      <MainLayout>
        <Head>
          <title>RYGLabs POC | About Us</title>
          <meta name='description' content='Generated by RYGLabs' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div style={{ height: '100vh' }}>About Page</div>
      </MainLayout>
    </>
  );
};
export default AboutPage;
